/*
  # Seed Annexe 4 — 222 règles de répartition extraites du PDF RSIF 27/05/2026

  Colonnes: ref_section, section_label, sous_section, nature_ouvrage, sous_ref, type_intervention, responsable
  Source: Annexe_4_-_Tableau_standard_de_repartition_des_charges_annexe_aux_baux.pdf
*/

INSERT INTO annexe4_regles (ref_section, section_label, sous_section, nature_ouvrage, sous_ref, type_intervention, responsable) VALUES

-- ─── SECTION 1 — CLOS, COUVERT ───────────────────────────────────────────────
-- 01-A Gros-oeuvre et structure
('01-A','Clos, Couvert','Gros-oeuvre et structure','Fondations',NULL,'Structure','Propriétaire'),
('01-A','Clos, Couvert','Gros-oeuvre et structure','Vide-sanitaire','a','Accès (trappe, porte…)','Gestionnaire'),
('01-A','Clos, Couvert','Gros-oeuvre et structure','Vide-sanitaire','b','Vide-sanitaire (circulations)','Propriétaire'),
('01-A','Clos, Couvert','Gros-oeuvre et structure','Murs porteurs',NULL,'Structure','Propriétaire'),
('01-A','Clos, Couvert','Gros-oeuvre et structure','Génie civil locaux techniques',NULL,'Structure','Propriétaire'),
('01-A','Clos, Couvert','Gros-oeuvre et structure','Façades (y compris bandeaux et acrotères)',NULL,'Structure','Propriétaire'),
('01-A','Clos, Couvert','Gros-oeuvre et structure','Planchers (dalles, etc…)',NULL,'Structure','Propriétaire'),
('01-A','Clos, Couvert','Gros-oeuvre et structure','Escaliers (y compris escaliers de secours)',NULL,'Structure','Propriétaire'),

-- 01-B Maçonnerie intérieure
('01-B','Clos, Couvert','Maçonnerie intérieure','Cloisons','a','Restructuration ou modification','Propriétaire'),
('01-B','Clos, Couvert','Maçonnerie intérieure','Cloisons','b','Réfection','Gestionnaire'),
('01-B','Clos, Couvert','Maçonnerie intérieure','Isolation par l''intérieur','a','Création','Propriétaire'),
('01-B','Clos, Couvert','Maçonnerie intérieure','Isolation par l''intérieur','b','Modification','Gestionnaire'),
('01-B','Clos, Couvert','Maçonnerie intérieure','Isolation par l''intérieur','c','Réfection','Gestionnaire'),

-- 01-C Couverture - étanchéité
('01-C','Clos, Couvert','Couverture - étanchéité','Charpente','a','Réfection complète','Propriétaire'),
('01-C','Clos, Couvert','Couverture - étanchéité','Charpente','b','Réfection partielle','Propriétaire'),
('01-C','Clos, Couvert','Couverture - étanchéité','Charpente','c','Réparation ou Entretien','Propriétaire'),
('01-C','Clos, Couvert','Couverture - étanchéité','Couverture','a','Réfection complète','Propriétaire'),
('01-C','Clos, Couvert','Couverture - étanchéité','Couverture','b','Réfection partielle','Propriétaire'),
('01-C','Clos, Couvert','Couverture - étanchéité','Couverture','c','Réparation ou Entretien','Propriétaire'),
('01-C','Clos, Couvert','Couverture - étanchéité','Toiture terrasse - étanchéité','a','Réfection complète','Propriétaire'),
('01-C','Clos, Couvert','Couverture - étanchéité','Toiture terrasse - étanchéité','b','Réfection partielle ou réparation ponctuelle','Propriétaire'),
('01-C','Clos, Couvert','Couverture - étanchéité','Toiture terrasse - étanchéité','c','Entretien','Gestionnaire'),
('01-C','Clos, Couvert','Couverture - étanchéité','Toiture terrasse : isolation','a','Pose','Propriétaire'),
('01-C','Clos, Couvert','Couverture - étanchéité','Toiture terrasse : isolation','b','Réfection complète','Propriétaire'),
('01-C','Clos, Couvert','Couverture - étanchéité','Toiture terrasse : isolation','c','Réfection partielle ou réparation ponctuelle','Propriétaire'),
('01-C','Clos, Couvert','Couverture - étanchéité','Acrotères, pénétrations',NULL,'Réfection','Propriétaire'),
('01-C','Clos, Couvert','Couverture - étanchéité','Joints de dilatation (étanchéité)',NULL,'Réfection','Propriétaire'),
('01-C','Clos, Couvert','Couverture - étanchéité','Descentes EP, Cheneaux','a','Réfection ou remplacement','Propriétaire'),
('01-C','Clos, Couvert','Couverture - étanchéité','Descentes EP, Cheneaux','b','Entretien','Gestionnaire'),
('01-C','Clos, Couvert','Couverture - étanchéité','Edicules techniques',NULL,'Réfection','Propriétaire'),
('01-C','Clos, Couvert','Couverture - étanchéité','Protections sécurité (crinolines)','a','Mise en place','Propriétaire'),
('01-C','Clos, Couvert','Couverture - étanchéité','Protections sécurité (crinolines)','b','Remplacement','Propriétaire'),
('01-C','Clos, Couvert','Couverture - étanchéité','Protections sécurité (crinolines)','c','Entretien','Gestionnaire'),

-- 01-D Façades (hors structures)
('01-D','Clos, Couvert','Façades (hors structures)','Revêtements + isolation extérieures','a','Pose','Propriétaire'),
('01-D','Clos, Couvert','Façades (hors structures)','Revêtements + isolation extérieures','b','Remplacement ou réfection complète','Propriétaire'),
('01-D','Clos, Couvert','Façades (hors structures)','Revêtements + isolation extérieures','c','Réparation ponctuelle','Gestionnaire'),
('01-D','Clos, Couvert','Façades (hors structures)','Revêtements + isolation extérieures','d','Entretien + Lavage','Gestionnaire'),
('01-D','Clos, Couvert','Façades (hors structures)','Revêtement façade sans isolation extérieure','a','Réfection / Ravalement complet','Propriétaire'),
('01-D','Clos, Couvert','Façades (hors structures)','Revêtement façade sans isolation extérieure','b','Réparation ponctuelle','Gestionnaire'),
('01-D','Clos, Couvert','Façades (hors structures)','Revêtement façade sans isolation extérieure','c','Entretien + Lavage','Gestionnaire'),

-- 01-E Menuiseries extérieures
('01-E','Clos, Couvert','Menuiseries extérieures','Menuiseries extérieures : fenêtres','a','Remplacement généralisé','Propriétaire'),
('01-E','Clos, Couvert','Menuiseries extérieures','Menuiseries extérieures : fenêtres','b','Remplacement ponctuel','Propriétaire'),
('01-E','Clos, Couvert','Menuiseries extérieures','Menuiseries extérieures : fenêtres','c','Réparation et entretien','Gestionnaire'),
('01-E','Clos, Couvert','Menuiseries extérieures','Protections (volets, etc…), occultations','a','Remplacement généralisé','Propriétaire'),
('01-E','Clos, Couvert','Menuiseries extérieures','Protections (volets, etc…), occultations','b','Remplacement ponctuel','Propriétaire'),
('01-E','Clos, Couvert','Menuiseries extérieures','Protections (volets, etc…), occultations','c','Réparation et entretien','Gestionnaire'),
('01-E','Clos, Couvert','Menuiseries extérieures','Joints, Quincaillerie','a','Remplacement','Gestionnaire'),
('01-E','Clos, Couvert','Menuiseries extérieures','Joints, Quincaillerie','b','Réparation et entretien','Gestionnaire'),
('01-E','Clos, Couvert','Menuiseries extérieures','Fermetures à rez de chaussée','a','Installation','Gestionnaire'),
('01-E','Clos, Couvert','Menuiseries extérieures','Fermetures à rez de chaussée','b','Remplacement','Gestionnaire'),
('01-E','Clos, Couvert','Menuiseries extérieures','Fermetures à rez de chaussée','c','Réparation et entretien','Gestionnaire'),

-- 01-F Menuiseries intérieures
('01-F','Clos, Couvert','Menuiseries intérieures','Parties communes','a','Remplacement','Gestionnaire'),
('01-F','Clos, Couvert','Menuiseries intérieures','Parties communes','b','Réparation','Gestionnaire'),
('01-F','Clos, Couvert','Menuiseries intérieures','Parties communes','c','Entretien','Gestionnaire'),
('01-F','Clos, Couvert','Menuiseries intérieures','Locaux techniques et autres gaines techniques','a','Remplacement','Gestionnaire'),
('01-F','Clos, Couvert','Menuiseries intérieures','Locaux techniques et autres gaines techniques','b','Réparation','Gestionnaire'),
('01-F','Clos, Couvert','Menuiseries intérieures','Locaux techniques et autres gaines techniques','c','Entretien','Gestionnaire'),
('01-F','Clos, Couvert','Menuiseries intérieures','Parties privatives','a','Remplacement','Gestionnaire'),
('01-F','Clos, Couvert','Menuiseries intérieures','Parties privatives','b','Réparation','Gestionnaire'),
('01-F','Clos, Couvert','Menuiseries intérieures','Parties privatives','c','Entretien','Gestionnaire'),

-- 01-G Serrurerie (métallerie, sécurité)
('01-G','Clos, Couvert','Serrurerie (métallerie, sécurité)','Parties communes et privatives','a','Remplacement','Gestionnaire'),
('01-G','Clos, Couvert','Serrurerie (métallerie, sécurité)','Parties communes et privatives','b','Réparation et entretien','Gestionnaire'),
('01-G','Clos, Couvert','Serrurerie (métallerie, sécurité)','Locaux techniques et autres','a','Remplacement','Gestionnaire'),
('01-G','Clos, Couvert','Serrurerie (métallerie, sécurité)','Locaux techniques et autres','b','Réparation et entretien','Gestionnaire'),
('01-G','Clos, Couvert','Serrurerie (métallerie, sécurité)','Cas spécifiques (ex : garde-corps)','a','Remplacement total','Propriétaire'),
('01-G','Clos, Couvert','Serrurerie (métallerie, sécurité)','Cas spécifiques (ex : garde-corps)','b','Remplacement ponctuel','Gestionnaire'),
('01-G','Clos, Couvert','Serrurerie (métallerie, sécurité)','Cas spécifiques (ex : garde-corps)','c','Réparation et entretien','Gestionnaire'),

-- ─── SECTION 2 — EQUIPEMENTS TECHNIQUES ──────────────────────────────────────
-- 02-A Production chauffage - ECS
('02-A','Équipements Techniques','Production chauffage - ECS','Energie (gaz, Fuel…) / Changement d''énergie','a','Réfection complète','Propriétaire'),
('02-A','Équipements Techniques','Production chauffage - ECS','Energie (gaz, Fuel…) / Changement d''énergie','b','Réfection partielle','Gestionnaire'),
('02-A','Équipements Techniques','Production chauffage - ECS','Energie (gaz, Fuel…) / Changement d''énergie','c','Réparation et Entretien','Gestionnaire'),
('02-A','Équipements Techniques','Production chauffage - ECS','Production chauffage (P3 - gestionnaire)','a','Installation','Propriétaire'),
('02-A','Équipements Techniques','Production chauffage - ECS','Production chauffage (P3 - gestionnaire)','b','Remplacement total','Propriétaire'),
('02-A','Équipements Techniques','Production chauffage - ECS','Production chauffage (P3 - gestionnaire)','c','Réfection partielle','Gestionnaire'),
('02-A','Équipements Techniques','Production chauffage - ECS','Production chauffage (P3 - gestionnaire)','d','Réparation et Entretien','Gestionnaire'),
('02-A','Équipements Techniques','Production chauffage - ECS','Distribution chauffage','a','Installation','Propriétaire'),
('02-A','Équipements Techniques','Production chauffage - ECS','Distribution chauffage','b','Remplacement','Propriétaire'),
('02-A','Équipements Techniques','Production chauffage - ECS','Distribution chauffage','c','Réfection partielle','Gestionnaire'),
('02-A','Équipements Techniques','Production chauffage - ECS','Distribution chauffage','d','Réparation et Entretien','Gestionnaire'),
('02-A','Équipements Techniques','Production chauffage - ECS','Radiateurs (ou réseau sols)','a','Installation','Propriétaire'),
('02-A','Équipements Techniques','Production chauffage - ECS','Radiateurs (ou réseau sols)','b','Remplacement total','Propriétaire'),
('02-A','Équipements Techniques','Production chauffage - ECS','Radiateurs (ou réseau sols)','c','Remplacement partiel','Gestionnaire'),
('02-A','Équipements Techniques','Production chauffage - ECS','Radiateurs (ou réseau sols)','d','Réparation et Entretien','Gestionnaire'),
('02-A','Équipements Techniques','Production chauffage - ECS','Production ECS','a','Installation','Propriétaire'),
('02-A','Équipements Techniques','Production chauffage - ECS','Production ECS','b','Remplacement total','Propriétaire'),
('02-A','Équipements Techniques','Production chauffage - ECS','Production ECS','c','Réfection partielle','Gestionnaire'),
('02-A','Équipements Techniques','Production chauffage - ECS','Production ECS','d','Réparation et Entretien','Gestionnaire'),
('02-A','Équipements Techniques','Production chauffage - ECS','Distribution ECS','a','Installation','Propriétaire'),
('02-A','Équipements Techniques','Production chauffage - ECS','Distribution ECS','b','Remplacement total','Propriétaire'),
('02-A','Équipements Techniques','Production chauffage - ECS','Distribution ECS','c','Réfection partielle','Gestionnaire'),
('02-A','Équipements Techniques','Production chauffage - ECS','Distribution ECS','d','Réparation et Entretien','Gestionnaire'),
('02-A','Équipements Techniques','Production chauffage - ECS','Divers : ex : Pompes…','a','Création','Gestionnaire'),
('02-A','Équipements Techniques','Production chauffage - ECS','Divers : ex : Pompes…','b','Réparation et Entretien','Gestionnaire'),

-- 02-B Plomberie Sanitaire
('02-B','Équipements Techniques','Plomberie Sanitaire','Réseau extérieur','a','Réfection complète','Propriétaire'),
('02-B','Équipements Techniques','Plomberie Sanitaire','Réseau extérieur','b','Réfection partielle','Propriétaire'),
('02-B','Équipements Techniques','Plomberie Sanitaire','Réseau extérieur','c','Réparation et Entretien','Gestionnaire'),
('02-B','Équipements Techniques','Plomberie Sanitaire','Réseau EF','a','Réfection complète','Propriétaire'),
('02-B','Équipements Techniques','Plomberie Sanitaire','Réseau EF','b','Réfection partielle','Gestionnaire'),
('02-B','Équipements Techniques','Plomberie Sanitaire','Réseau EF','c','Réparation et Entretien','Gestionnaire'),
('02-B','Équipements Techniques','Plomberie Sanitaire','Appareils sanitaires et robinetterie','a','Renouvellement généralisé','Gestionnaire'),
('02-B','Équipements Techniques','Plomberie Sanitaire','Appareils sanitaires et robinetterie','b','Renouvellement partiel','Gestionnaire'),
('02-B','Équipements Techniques','Plomberie Sanitaire','Appareils sanitaires et robinetterie','c','Réparation et Entretien','Gestionnaire'),
('02-B','Équipements Techniques','Plomberie Sanitaire','Evacuations','a','Réfection complète','Propriétaire'),
('02-B','Équipements Techniques','Plomberie Sanitaire','Evacuations','b','Réfection partielle','Gestionnaire'),
('02-B','Équipements Techniques','Plomberie Sanitaire','Evacuations','c','Réparation et Entretien','Gestionnaire'),
('02-B','Équipements Techniques','Plomberie Sanitaire','Divers : Ex : traitement d''eau','a','Création','Propriétaire'),
('02-B','Équipements Techniques','Plomberie Sanitaire','Divers : Ex : traitement d''eau','b','Remplacement','Gestionnaire'),
('02-B','Équipements Techniques','Plomberie Sanitaire','Divers : Ex : traitement d''eau','c','Réparation et Entretien','Gestionnaire'),

-- 02-C Ventilation mécanique contrôlée
('02-C','Équipements Techniques','Ventilation mécanique contrôlée','Extracteurs (en toiture)','a','Remplacement','Propriétaire'),
('02-C','Équipements Techniques','Ventilation mécanique contrôlée','Extracteurs (en toiture)','b','Réparation et Entretien','Gestionnaire'),
('02-C','Équipements Techniques','Ventilation mécanique contrôlée','Réseau extérieur (en toiture) et intérieur','a','Réfection complète','Propriétaire'),
('02-C','Équipements Techniques','Ventilation mécanique contrôlée','Réseau extérieur (en toiture) et intérieur','b','Réfection partielle','Gestionnaire'),
('02-C','Équipements Techniques','Ventilation mécanique contrôlée','Réseau extérieur (en toiture) et intérieur','c','Réparation et Entretien','Gestionnaire'),
('02-C','Équipements Techniques','Ventilation mécanique contrôlée','Appareillage : bouches d''extractions','a','Renouvellement','Gestionnaire'),
('02-C','Équipements Techniques','Ventilation mécanique contrôlée','Appareillage : bouches d''extractions','b','Réparation','Gestionnaire'),
('02-C','Équipements Techniques','Ventilation mécanique contrôlée','Appareillage : bouches d''extractions','c','Entretien (nettoyage)','Gestionnaire'),
('02-C','Équipements Techniques','Ventilation mécanique contrôlée','Appareillage : entrées d''air','a','Réfection','Gestionnaire'),
('02-C','Équipements Techniques','Ventilation mécanique contrôlée','Appareillage : entrées d''air','b','Réparation','Gestionnaire'),
('02-C','Équipements Techniques','Ventilation mécanique contrôlée','Appareillage : entrées d''air','c','Entretien (nettoyage)','Gestionnaire'),
('02-C','Équipements Techniques','Ventilation mécanique contrôlée','Ventilation spécifiques cuisines','a','Réfection complète','Gestionnaire'),
('02-C','Équipements Techniques','Ventilation mécanique contrôlée','Ventilation spécifiques cuisines','b','Réfection ponctuelle','Gestionnaire'),
('02-C','Équipements Techniques','Ventilation mécanique contrôlée','Ventilation spécifiques cuisines','c','Réparation et Entretien','Gestionnaire'),
('02-C','Équipements Techniques','Ventilation mécanique contrôlée','Ventilation statique (cas particulier)',NULL,'(cas particulier)','Gestionnaire'),

-- 02-D Electricité courants forts
('02-D','Équipements Techniques','Électricité courants forts','Transformateur','NULL','EDF / Réseau','Propriétaire'),
('02-D','Équipements Techniques','Électricité courants forts','Local TGBT',NULL,'(aucun type précisé)','Gestionnaire'),
('02-D','Équipements Techniques','Électricité courants forts','Comptage protection','a','Réfection complète','Gestionnaire'),
('02-D','Équipements Techniques','Électricité courants forts','Comptage protection','b','Réfection ponctuelle','Gestionnaire'),
('02-D','Équipements Techniques','Électricité courants forts','Comptage protection','c','Réparation et Entretien','Gestionnaire'),
('02-D','Équipements Techniques','Électricité courants forts','Distribution Courants forts','a','Réfection complète','Propriétaire'),
('02-D','Équipements Techniques','Électricité courants forts','Distribution Courants forts','b','Réfection partielle','Gestionnaire'),
('02-D','Équipements Techniques','Électricité courants forts','Distribution Courants forts','c','Réparation et Entretien','Gestionnaire'),
('02-D','Équipements Techniques','Électricité courants forts','Appareillage Parties communes et privatives','a','Réfection complète','Gestionnaire'),
('02-D','Équipements Techniques','Électricité courants forts','Appareillage Parties communes et privatives','b','Réfection ponctuelle','Gestionnaire'),
('02-D','Équipements Techniques','Électricité courants forts','Appareillage Parties communes et privatives','c','Réparation et Entretien','Gestionnaire'),
('02-D','Équipements Techniques','Électricité courants forts','Appareillage parties spécifiques (ex : cuisines)','a','Réfection complète','Gestionnaire'),
('02-D','Équipements Techniques','Électricité courants forts','Appareillage parties spécifiques (ex : cuisines)','b','Réfection ponctuelle','Gestionnaire'),
('02-D','Équipements Techniques','Électricité courants forts','Appareillage parties spécifiques (ex : cuisines)','c','Réparation et Entretien','Gestionnaire'),
('02-D','Équipements Techniques','Électricité courants forts','Eclairage extérieur','a','Réfection complète','Propriétaire'),
('02-D','Équipements Techniques','Électricité courants forts','Eclairage extérieur','b','Réfection partielle','Gestionnaire'),
('02-D','Équipements Techniques','Électricité courants forts','Eclairage extérieur','c','Réparation et Entretien','Gestionnaire'),

-- 02-E Electricité courants faibles
('02-E','Équipements Techniques','Électricité courants faibles (tél + TV)','Distribution courants faibles','a','Installation','Gestionnaire'),
('02-E','Équipements Techniques','Électricité courants faibles (tél + TV)','Distribution courants faibles','b','Réfection complète','Gestionnaire'),
('02-E','Équipements Techniques','Électricité courants faibles (tél + TV)','Distribution courants faibles','c','Réfection partielle, Réparation, Entretien','Gestionnaire'),
('02-E','Équipements Techniques','Électricité courants faibles (tél + TV)','Appareillage parties communes et privatives','a','Installation','Gestionnaire'),
('02-E','Équipements Techniques','Électricité courants faibles (tél + TV)','Appareillage parties communes et privatives','b','Réfection complète','Gestionnaire'),
('02-E','Équipements Techniques','Électricité courants faibles (tél + TV)','Appareillage parties communes et privatives','c','Réfection partielle, Réparation, Entretien','Gestionnaire'),
('02-E','Équipements Techniques','Électricité courants faibles (tél + TV)','Parties spécifiques (ex : cabines téléph.)','a','Installation','Gestionnaire'),
('02-E','Équipements Techniques','Électricité courants faibles (tél + TV)','Parties spécifiques (ex : cabines téléph.)','b','Réfection complète','Gestionnaire'),
('02-E','Équipements Techniques','Électricité courants faibles (tél + TV)','Parties spécifiques (ex : cabines téléph.)','c','Réfection partielle, Réparation, Entretien','Gestionnaire'),

-- 02-F Electricité autres cas
('02-F','Équipements Techniques','Électricité - autres cas','ex : Sonorisation','a','Installation','Gestionnaire'),
('02-F','Équipements Techniques','Électricité - autres cas','ex : Sonorisation','b','Réfection complète','Gestionnaire'),
('02-F','Équipements Techniques','Électricité - autres cas','ex : Sonorisation','c','Réfection partielle, Réparation, Entretien','Gestionnaire'),

-- 02-G Ascenseurs
('02-G','Équipements Techniques','Ascenseurs','Machinerie','a','Remplacement et mise aux normes','Propriétaire'),
('02-G','Équipements Techniques','Ascenseurs','Machinerie','b','Réparation','Gestionnaire'),
('02-G','Équipements Techniques','Ascenseurs','Machinerie','c','Entretien','Gestionnaire'),
('02-G','Équipements Techniques','Ascenseurs','Cabines, portes palières','a','Remplacement et mise aux normes','Propriétaire'),
('02-G','Équipements Techniques','Ascenseurs','Cabines, portes palières','b','Réparation','Gestionnaire'),
('02-G','Équipements Techniques','Ascenseurs','Cabines, portes palières','c','Entretien','Gestionnaire'),

-- 02-H Evacuation des ordures
('02-H','Équipements Techniques','Évacuation des ordures ménagères','Pelles vide-ordures','a','Remplacement','Gestionnaire'),
('02-H','Équipements Techniques','Évacuation des ordures ménagères','Pelles vide-ordures','b','Réparation, Entretien','Gestionnaire'),
('02-H','Équipements Techniques','Évacuation des ordures ménagères','Gaines et réception vide-ordures','a','Réfection complète','Gestionnaire'),
('02-H','Équipements Techniques','Évacuation des ordures ménagères','Gaines et réception vide-ordures','b','Réfection partielle, réparation, entretien','Gestionnaire'),
('02-H','Équipements Techniques','Évacuation des ordures ménagères','Locaux ordures ménagères (ex : tri sélectif)','a','Installation','Propriétaire'),
('02-H','Équipements Techniques','Évacuation des ordures ménagères','Locaux ordures ménagères (ex : tri sélectif)','b','Réfection','Gestionnaire'),
('02-H','Équipements Techniques','Évacuation des ordures ménagères','Locaux ordures ménagères (ex : tri sélectif)','c','Réparation, Entretien','Gestionnaire'),
('02-H','Équipements Techniques','Évacuation des ordures ménagères','Evacuation des ordures ménagères',NULL,'selon ramassage municipal','Gestionnaire'),

-- 02-I Désinfection 3D
('02-I','Équipements Techniques','Désinfection 3D','Ensemble du bâtiment (sous-sol, gaines)',NULL,'(désinfection périodique)','Gestionnaire'),
('02-I','Équipements Techniques','Désinfection 3D','Vide-ordures',NULL,'(désinfection périodique)','Gestionnaire'),

-- ─── SECTION 3 — REVETEMENTS ──────────────────────────────────────────────────
-- 03-A Revêtements de sols
('03-A','Revêtements','Revêtements de sols','Parties communes','a','Remplacement total ou partiel','Gestionnaire'),
('03-A','Revêtements','Revêtements de sols','Parties communes','b','Entretien','Gestionnaire'),
('03-A','Revêtements','Revêtements de sols','Locaux techniques et autres','a','Remplacement total ou partiel','Gestionnaire'),
('03-A','Revêtements','Revêtements de sols','Locaux techniques et autres','b','Entretien','Gestionnaire'),
('03-A','Revêtements','Revêtements de sols','Parties privatives','a','Remplacement total ou partiel','Gestionnaire'),
('03-A','Revêtements','Revêtements de sols','Parties privatives','b','Entretien','Gestionnaire'),

-- 03-B Revêtements muraux
('03-B','Revêtements','Revêtements muraux','Parties communes','a','Remplacement total ou partiel','Gestionnaire'),
('03-B','Revêtements','Revêtements muraux','Parties communes','b','Entretien','Gestionnaire'),
('03-B','Revêtements','Revêtements muraux','Locaux techniques et autres','a','Remplacement total ou partiel','Gestionnaire'),
('03-B','Revêtements','Revêtements muraux','Locaux techniques et autres','b','Entretien','Gestionnaire'),
('03-B','Revêtements','Revêtements muraux','Parties privatives','a','Remplacement total ou partiel','Gestionnaire'),
('03-B','Revêtements','Revêtements muraux','Parties privatives','b','Entretien','Gestionnaire'),

-- 03-C Plafonds
('03-C','Revêtements','Plafonds (revêtements ou faux-plafonds)','Parties communes','a','Remplacement total ou partiel','Gestionnaire'),
('03-C','Revêtements','Plafonds (revêtements ou faux-plafonds)','Parties communes','b','Entretien','Gestionnaire'),
('03-C','Revêtements','Plafonds (revêtements ou faux-plafonds)','Locaux techniques et autres','a','Remplacement total ou partiel','Gestionnaire'),
('03-C','Revêtements','Plafonds (revêtements ou faux-plafonds)','Locaux techniques et autres','b','Entretien','Gestionnaire'),
('03-C','Revêtements','Plafonds (revêtements ou faux-plafonds)','Parties privatives','a','Remplacement total ou partiel','Gestionnaire'),
('03-C','Revêtements','Plafonds (revêtements ou faux-plafonds)','Parties privatives','b','Entretien','Gestionnaire'),

-- ─── SECTION 4 — AMENAGEMENTS EXTERIEURS ─────────────────────────────────────
('04','Aménagements Extérieurs',NULL,'Clôture ou murs d''enceinte','a','Remplacement','Propriétaire'),
('04','Aménagements Extérieurs',NULL,'Clôture ou murs d''enceinte','b','Réfection partielle, Réparation','Gestionnaire'),
('04','Aménagements Extérieurs',NULL,'Clôture ou murs d''enceinte','c','Entretien','Gestionnaire'),
('04','Aménagements Extérieurs',NULL,'Accès (ex : barrières ou portail…)','a','Remplacement','Propriétaire'),
('04','Aménagements Extérieurs',NULL,'Accès (ex : barrières ou portail…)','b','Réparation, Entretien','Gestionnaire'),
('04','Aménagements Extérieurs',NULL,'Voirie et stationnement (en surface)','a','Réfection complète','Propriétaire'),
('04','Aménagements Extérieurs',NULL,'Voirie et stationnement (en surface)','b','Réfection partielle','Gestionnaire'),
('04','Aménagements Extérieurs',NULL,'Voirie et stationnement (en surface)','c','Réparation et entretien','Gestionnaire'),
('04','Aménagements Extérieurs',NULL,'Stationnement extérieur fermé (box, garages)','a','Réfection complète','Propriétaire'),
('04','Aménagements Extérieurs',NULL,'Stationnement extérieur fermé (box, garages)','b','Réfection partielle','Gestionnaire'),
('04','Aménagements Extérieurs',NULL,'Stationnement extérieur fermé (box, garages)','c','Réparation et entretien','Gestionnaire'),
('04','Aménagements Extérieurs',NULL,'Equipements extérieurs (aires de jeux, bancs…)','a','Réfection complète','Gestionnaire'),
('04','Aménagements Extérieurs',NULL,'Equipements extérieurs (aires de jeux, bancs…)','b','Réfection partielle','Gestionnaire'),
('04','Aménagements Extérieurs',NULL,'Equipements extérieurs (aires de jeux, bancs…)','c','Réparation et entretien','Gestionnaire'),
('04','Aménagements Extérieurs',NULL,'Espaces verts','a','Remplacement ou transformation','Gestionnaire'),
('04','Aménagements Extérieurs',NULL,'Espaces verts','b','Entretien (taille, élagage, abattage)','Propriétaire'),
('04','Aménagements Extérieurs',NULL,'Espaces verts','c','Désouchage, traitement racines','Propriétaire'),

-- ─── SECTION 5 — SECURITE ────────────────────────────────────────────────────
('05','Sécurité',NULL,'Isolation coupe-feu, encloisonnement','a','Création','Propriétaire'),
('05','Sécurité',NULL,'Isolation coupe-feu, encloisonnement','b','Remplacement','Gestionnaire'),
('05','Sécurité',NULL,'Isolation coupe-feu, encloisonnement','c','Réparation et Entretien','Gestionnaire'),
('05','Sécurité',NULL,'Désenfumage','a','Création','Propriétaire'),
('05','Sécurité',NULL,'Désenfumage','b','Remplacement','Gestionnaire'),
('05','Sécurité',NULL,'Désenfumage','c','Réparation et Entretien','Gestionnaire'),
('05','Sécurité',NULL,'RIA, Colonnes sèches','a','Création','Propriétaire'),
('05','Sécurité',NULL,'RIA, Colonnes sèches','b','Remplacement','Gestionnaire'),
('05','Sécurité',NULL,'RIA, Colonnes sèches','c','Réparation et Entretien','Gestionnaire'),
('05','Sécurité',NULL,'Alarmes incendie','a','Création','Propriétaire'),
('05','Sécurité',NULL,'Alarmes incendie','b','Remplacement','Gestionnaire'),
('05','Sécurité',NULL,'Alarmes incendie','c','Réparation et Entretien','Gestionnaire'),
('05','Sécurité',NULL,'Détection incendie','a','Création','Propriétaire'),
('05','Sécurité',NULL,'Détection incendie','b','Réparation, Remplacement','Gestionnaire'),
('05','Sécurité',NULL,'Détection incendie','c','Entretien','Gestionnaire'),
('05','Sécurité',NULL,'Eclairage de sécurité','a','Création','Propriétaire'),
('05','Sécurité',NULL,'Eclairage de sécurité','b','Réparation, Remplacement','Gestionnaire'),
('05','Sécurité',NULL,'Eclairage de sécurité','c','Entretien','Gestionnaire'),
('05','Sécurité',NULL,'Signalisation','a','Création','Gestionnaire'),
('05','Sécurité',NULL,'Signalisation','b','Réparation, Remplacement','Gestionnaire'),
('05','Sécurité',NULL,'Signalisation','c','Entretien','Gestionnaire'),
('05','Sécurité',NULL,'Extincteurs','a','Installation','Gestionnaire'),
('05','Sécurité',NULL,'Extincteurs','b','Remplacement','Gestionnaire'),
('05','Sécurité',NULL,'Extincteurs','c','Entretien','Gestionnaire'),
('05','Sécurité',NULL,'Equipements à l''extérieur (bornes incendie)','a','Création','Propriétaire'),
('05','Sécurité',NULL,'Equipements à l''extérieur (bornes incendie)','b','Réparation et entretien','Gestionnaire'),

-- ─── SECTION 6 — EQUIPEMENTS DIVERS ─────────────────────────────────────────
('06','Équipements Divers',NULL,'Cabines sanitaires multifonctions','a','Remplacement','Gestionnaire'),
('06','Équipements Divers',NULL,'Cabines sanitaires multifonctions','b','Réparation','Gestionnaire'),
('06','Équipements Divers',NULL,'Cabines sanitaires multifonctions','c','Entretien','Gestionnaire'),
('06','Équipements Divers',NULL,'Mobilier','a','Création, Remplacement','Gestionnaire'),
('06','Équipements Divers',NULL,'Mobilier','b','Réparation','Gestionnaire'),
('06','Équipements Divers',NULL,'Mobilier','c','Entretien','Gestionnaire'),
('06','Équipements Divers',NULL,'Laverie','a','Création, Remplacement','Gestionnaire'),
('06','Équipements Divers',NULL,'Laverie','b','Réparation','Gestionnaire'),
('06','Équipements Divers',NULL,'Laverie','c','Entretien','Gestionnaire'),
('06','Équipements Divers',NULL,'Bar','a','Création, Remplacement','Gestionnaire'),
('06','Équipements Divers',NULL,'Bar','b','Réparation','Gestionnaire'),
('06','Équipements Divers',NULL,'Bar','c','Entretien','Gestionnaire'),
('06','Équipements Divers',NULL,'Cuisines','a','Création, Remplacement','Gestionnaire'),
('06','Équipements Divers',NULL,'Cuisines','b','Réparation','Gestionnaire'),
('06','Équipements Divers',NULL,'Cuisines','c','Entretien','Gestionnaire'),
('06','Équipements Divers',NULL,'Autres équipements divers','a','Création, Remplacement','Gestionnaire'),
('06','Équipements Divers',NULL,'Autres équipements divers','b','Réparation','Gestionnaire'),
('06','Équipements Divers',NULL,'Autres équipements divers','c','Entretien','Gestionnaire');
